import { Theme } from '@mui/material';

const getFilmAdaptiveScheduleGridItemStyles = (theme: Theme) => ({
  sectionWrapper: {
    display: 'flex',
    flexDirection: 'row',
    gap: '6px',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  filmCardsWrapper: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    justifyContent: 'center',
    gap: '12px',
    padding: '12px 0',
  },
  filmCardItem: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    maxWidth: '280px',
    maxHeight: 'fit-content',
    margin: '0 auto',
  },
  filmPoster: {
    width: '100%',
    maxWidth: '100px',
    aspectRatio: '2 / 3',
    objectFit: 'cover',
  },
  filmPosterAltBox: {
    aspectRatio: '2 / 3',
    width: '100%',
    backgroundColor: '#555',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '4px 4px 0 0',
  },
  filmPosterAltText: {
    color: theme.palette.text.primary,
  },
  filmCardContent: {
    p: '6px !important',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    flex: 1,
  },
  filmTitle: {
    color: theme.palette.text.primary,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 1,
    WebkitBoxOrient: 'vertical',
    fontWeight: 600,
    fontSize: '1rem',
    minHeight: 'fit-content',
    lineHeight: 1.2,
    marginBottom: theme.spacing(1),
    cursor: 'pointer',
    width: 'fit-content',
    maxWidth: '228px',
    transiton: 'color 0.4s ease',
    '&:hover': {
      color: theme.palette.primary.dark,
      transition: 'color 0.4s ease',
    },
  },
  sessionPriceInfo: {
    backgroundColor: theme.palette.primary.dark,
    borderRadius: '5px',
    width: 'fit-content',
    p: '2px 6px',
  },
  sessionPriceText: {
    fontSize: '0.75rem',
    color: theme.palette.primary.light,
    whiteSpace: 'nowrap',
  },
  filmTimeText: {
    fontSize: 'clamp(0.75rem, 1.5vw, 1rem)',
    maxHeight: 'fit-content',
    color: theme.palette.primary.light,
    textAlign: 'center',
    transiton: 'color 0.4s ease',
    cursor: 'pointer',
    maxWidth: 'fit-content',
    '&:hover': {
      color: theme.palette.primary.dark,
      transition: 'color 0.4s ease',
    },
  },
  filmInfoContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    border: `1px solid ${theme.palette.primary.dark}`,
    justifyContent: 'center',

    borderRadius: '6px',
    padding: '6px',
    gap: '6px',
    width: '100%',
    height: '65px',
    maxHeight: '65px',
  },
  filmInfoContainerHelper: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    columnGap: '6px',
    rowGap: '0px',
    width: '100%',
    maxWidth: '145px',
    height: 'fit-content',
  },
});

export default getFilmAdaptiveScheduleGridItemStyles;
